### ISSUE TITLE
Microsoft C++ 异常: cv::Exception，位于内存位置 *****

### ISSUE THREAD

**Issue by czh55** [jiafeng5513/Evision#2]
您好！
错误位置在RulerView.cpp第61行`disp = RawDisp.at<uchar>(y, x);`，响应左键点击求取深度的时候。
当前的系统是window10_64,vs2017和作者的环境基本一致。
尝试修改了第170行`RawDisp.convertTo(disparityGary, CV_8UC3);`为CV_8UC4和CV_8UC2都出错。
请问问题可能出现在哪里呢？

**Comment by jiafeng5513** [comment]
您好
这是我程序里面的一个很麻烦的问题,原理是这样,要把Mat显示在Qt界面上,我测试的结果是只有CV_8U的Mat可以正常转换,但是我感觉你这个问题并没有说明白,最好能提供以下信息;
1. 使用的是哪个视差算法
2. 使用视差算法的时候,有没有勾选"输入已校正的图片"
3. 视差算法的输入图片是彩色的还是灰度的
4. 出问题的地方具体报了什么错误,以及你是怎么定位到这个错误的


发自安娜的秘密基地
在2019年3月21日 10:30，czh55<notifications@github.com><mailto:notifications@github.com> 写道：

您好！
错误位置在RulerView.cpp第61行disp = RawDisp.at<uchar>(y, x);，响应左键点击求取深度的时候。
当前的系统是window10_64,vs2017和作者的环境基本一致。
尝试修改了第170行RawDisp.convertTo(disparityGary, CV_8UC3);为CV_8UC4和CV_8UC2都出错。
请问问题可能出现在哪里呢？

**Comment by czh55** [comment]
1.重测试了BM，SGBM，ELAS，发现只有ELAS不报错，并且我都勾选了"输入已校正的图片"
2.我使用的照片是原有的宿舍的那张照片
3.在Debug模式下，当我点击左键准备获取深度信息时报错，报错内容如下
![image](https://user-images.githubusercontent.com/22538118/54731019-f6ef5a80-4bc6-11e9-9db6-124f85577bee.png)

**Comment by jiafeng5513** [comment]
感谢您反馈的问题,抱歉没及时回复!
这个问题是这样的,我之前写了一个转换格式的模板函数,但是那个函数转换BM和SGBM的视差图时会发生整数除法截断,导致视差图看起来偏白或者偏黑,所以我就临时改成了现在这个样子,我正在思考和实验怎么解决这个问题,如果您有思路,还请提供一下~
再次感谢!

**Comment by czh55** [comment]
抱歉，目前也还没有思路，也在尝试解决。如果有进展，我会及时告您。

**Comment by jiafeng5513** [comment]
该问题已经解决
