### ISSUE TITLE
大佬代码很规范，有没有教程可以推荐，是 QT版本的 MVC 框架么？

### ISSUE THREAD

**Issue by msnh2012** [jiafeng5513/Evision#3]

**Comment by jiafeng5513** [comment]
是Qt的MVC,教程的话,如果你指的是Qt的教程,可以到哔哩哔哩上找一下Qt的视频教程,如果觉得代码还行,麻烦给个星星~

发自安娜的秘密基地
在2019年5月16日 17:46，msnh<notifications@github.com><mailto:notifications@github.com> 写道：

**Comment by msnh2012** [comment]
给Star啦，主要是QT MVC这一块的实战吧，书上的东西太理论，有没有什么可以推荐的:D
