### ISSUE TITLE
哥们，这个dockwidget怎么填充满？

### ISSUE THREAD

**Issue by msnh2012** [jiafeng5513/Evision#4]
![image](https://user-images.githubusercontent.com/17841334/64322641-8bbf0680-cff5-11e9-8d09-1a253561cd56.png)

**Comment by jiafeng5513** [comment]
里面那个框的外层容器有四个属性,分别是上下左右的间距,用designer的时候在层级管理窗口里面能选到上层容器,直接点是点不到的.把他们设置到0.
