### ISSUE TITLE
有关相机参数输入，和adcensus算法参数：

### ISSUE THREAD

**Issue by ayu1121** [jiafeng5513/Evision#5]
请问两个相机旋转矩阵九个数是按照列的顺序输入的吗？
并且，adcensus算法里census的窗口大小是9×7
并且pi1是pi2是3，投票阈值是0.4不是4，我尝试把参数修改后可以得到更好效果的视差图

**Comment by jiafeng5513** [comment]
问题1:矩阵按照行优先的顺序,例如[[1,2,3],[4,5,6],[7,8,9]]=>[1,2,3,4,5,6,7,8,9]
您所述参数指的是您发现的一组较好的参数组合吗?如果是,感谢您的反馈.
