### ISSUE TITLE
错误	LNK1181：无法打开输入文件“...\EvisionUtils.lib"和“...\EvisionCalibrate.lib””

### ISSUE THREAD

**Issue by ssggle** [jiafeng5513/Evision#6]
用CMake进行build之后，打开编译后的工程进行生成（ALL_BUILD），但出现上面的错误，没有生成相应的两个文件库，请问可能是什么原因造成的？

**Comment by ssggle** [comment]
补充一下：环境是：vs2015+OpenCV4.3+QT5.9.1，PCL和CUDA点云那两个模块为启动

**Comment by jiafeng5513** [comment]
你给的信息不足以判断问题,PCL和CUDA和这两个目标文件是无关的,你可以尝试单独生成这两个项目,看一下错误信息是什么

**Comment by ssggle** [comment]
谢谢！已经解决了，把QT版本升级后编译通过了

**Comment by jiafeng5513** [comment]
好的
