### ISSUE TITLE
如何安装成哔哩哔哩中新版程序演示视频那样？新手能否给个教程？

### ISSUE THREAD

**Issue by PetershengWUHU** [jiafeng5513/Evision#7]

**Comment by fangxu622** [comment]
up 住视频演示的好像是MFC 版本，而现在这个是Qt 版本

**Comment by jiafeng5513** [comment]
B站上的视频有两个版本,可以点到我空间里面看,MFC版本的已经不再更新了,Qt版本的视频中带有Evision字样,安装过程在readme中已经写的很详细了,请仔细查看,有不明白的地方可以交流

**Comment by PetershengWUHU** [comment]
![image](https://user-images.githubusercontent.com/39899668/90107960-3306fa80-dd7c-11ea-8db3-90b1f20a175e.png)
我想请问一下，是因为相关属性没有配置么？
![image](https://user-images.githubusercontent.com/39899668/90108137-6ba6d400-dd7c-11ea-82e4-9d81e2bc67b6.png)
怎么配置？

**Comment by jiafeng5513** [comment]
这样提问我真的好难回答,我准备出一个更详细的CMake指南视频,另外程序里面有问题的那个模块目前已经默认跳过编译了,那是正在开发的部分,请大家关注更新,谢谢关注

**Comment by XiujunTang** [comment]
想问是否已经解决，我也是Qt库链接有问题，一直提示无法解析的外部命令
